- README.md
- src/index.ts
- test/doubleSlash.test.ts
- test/join.test.ts
> feat: add cleanDoubleSlash

- package.json
Seems like #7 has been reintroduced through https://github.com/unjs/ufo/commit/7c26571f0b5df2b93a694f4787cac4b6bdf73625.
This PR resolves it again (but there might be a better solution as it had been removed intentionally in https://github.com/unjs/ufo/commit/be3b1ae3a5880e5127006a7b86362fd833b4992a ?).
Resolves: https://github.com/nuxt/framework/issues/118
> fix: allow pkg subpath import

- src/encoding.ts
- src/url.ts
- test/normalize.test.ts
Fix for issue https://github.com/unjs/ufo/issues/22
Only preventing decoding of encoded slash in pathname part of URL.
> fix: slash encode in path

- README.md
Fixes #26
[Tested on Runkit with version 0.7.5](https://runkit.com/bokub/parseurl-tests)
> docs: add `parseURL` examples

- README.md
- src/utils.ts
- test/trailing-slash.test.ts
resolves #19
Support `ufo.withTrailingSlash('/path?a=1')` to be `/path?a=1/` when second argument is passed `true`
Downsides:
- Might introduce unwanted behavior when input is not URL (example: `/:param?` ~> `/:param/?`)
- Adding runtime overhead for cases that do not need this feature
> feat: support query params for `trailingSlash` utils

- README.md
- src/utils.ts
- test/utilities.test.ts
> feat: withHttp, withHttps, withoutProtocol, withProtocol

- src/query.ts
- test/query.test.ts
Handle boolean values in encodeQueryItem.
I was also wondering why not simply using the native URLSearchParams interface to encode query params ?
> fix(encodeQueryItem): stringify boolean values

- src/query.ts
- test/query.test.ts
> feat: remove undefined from withQuery

- src/encoding.ts
- test/query.test.ts
Possible fix for encoding correctly query values.
Closes #105
> fix: encode `[]` and `{}` in query values to increase compatibility

- src/parse.ts
- src/utils.ts
- test/utilities.test.ts
Resolves #70
Using `hasProtocol('..', { strict: true })` we require that protocol url ends with at least one slash.
> feat(hasProtocol): strict mode support

- src/encoding.ts
- src/query.ts
- src/url.ts
- test/query.test.ts
resolves #41 resolves #62
rework and closes #72
Currently (same as URLSearchParams) if input is not string/number, we encode it to something like `foo=%5Bobject+Object%5D` which is useless! 
There is no standard spec, however this PR solves it with simplest method of using `JSON.stringify`
> feat: stringify query values

- src/parse.ts
> docs: add jsdocs for parse utils

- src/encoding.ts
- src/query.ts
- test/encoding.test.ts
- test/query.test.ts
Added support to decode query params key properly.
Fixed: https://github.com/unjs/ufo/issues/149
> fix(parseQuery): decode space in query keys

- src/utils.ts
https://github.com/nuxt/nuxt/pull/22366
This allows checking for protocol existence with `hasProtocol('https://test.com', { script: false })`, in cases where we want to safely redirect to an external URL.
API thoughts welcome.
> feat: add `isScriptProtocol` util

- README.md
- src/parse.ts
- test/parse.test.ts
> feat: add `parseFilename` utility

- src/parse.ts
- test/parse.test.ts
Resolves #158
As `parseURL` accept an ambegious input (path or URL), we cannot allow all `proto:...` without `proto://` syntax. This PR adds special handler check for `data` and `blob`
> fix(parseURL): handle `data:` and `blob` protocols

- src/parse.ts
- src/utils.ts
- test/normalize.test.ts
- test/parse.test.ts
- test/utilities.test.ts
A couple of linked fixes with parsing protocols in URLs: https://url.spec.whatwg.org/#scheme-state
Thanks to @OhB00.
> fix(parseURL, hasProtocol, isScriptProtocol): ignore leading whitespaces

- src/utils.ts
- test/utilities.test.ts
This addresses an issue where something like `'javaScript:alert(document.domain)'` would not register as a script protocol owing to case sensitivity.
> fix: test script protocols insensitively

- src/parse.ts
- test/parse.test.ts
https://github.com/unjs/ufo/pull/180
https://github.com/nuxt/nuxt/pull/24288
This applies fix on case sensitivity to `parseURL`
> fix(parseURL): parse protocol case-insensitively

- test/url.test.ts
> tests: add the tests for `$URL`

- README.md
- src/utils.ts
- test/utilities.test.ts
Fixes #211.
Removes the host from the input URL.
> feat: add `withoutHost` utility

- src/utils.ts
- test/base.test.ts
- test/join.test.ts
As a continuation to #217 (to resolve #37), this PR reimplements `joinURL` utility with more clear syntax and basic support for relative `../` segments
**Behavior change:** For `joinURL` and `withBase`, the trailing slash of base is always respected. It is more of a bug fix.
> refactor(joinURL): rewrite with clear syntax and relative `../` support

- README.md
- src/utils.ts
- test/base.test.ts
- test/join.test.ts
Context: #37 > #217 > #218 
This PR reverts back `joinURL` behavior to 1.4.0 (latest release) and adds support of joining URLs with relative `../` paths with new `joinRelativeURL` utility.
The reason for this decision is to avoid potential behavior changes as the current `joinURL` behavior is depended in many places. (also `resolveURL` and `normalize` need to follow a consistent change)
In next major release we might join behavior (but if anything diverging from `joinRelativeURL`, we keep it's behavior as is for `joinRelativeURL` to not break another segment of usages)
> feat: `joinRelativeURL`

- src/utils.ts
- test/trailing-slash.test.ts
> fix(withoutTrailingSlash): consider qurry param 

- README.md
- src/utils.ts
- test/join.test.ts
> fix(joinRelativeURL): handle base with protocol

- src/utils.ts
hotfix to resolve #224
**Note:** Lookbehind syntax is supported in majority of browsers ([caniuse](https://caniuse.com/js-regexp-lookbehind)) and this is a temporary solution until discussing more.
> fix: use lookbehind regex only inside `joinRelativeURL`

- src/utils.ts
- test/join.test.ts
Related to https://github.com/unjs/ufo/issues/224m, https://github.com/nuxt/nuxt/issues/26393
This PR rewrites `joinRelativeURL` logic to avoid Regex with look behind for safari <= 16.3 compatibility.
> fix(joinRelativeURL): avoid lookbehind regex for browser compatibility

- src/parse.ts
- test/parse.test.ts
Issue: https://github.com/unjs/ufo/issues/247
URL paths which include a colon as the second character are falsely included in the fix for windows path URLs [here](https://github.com/unjs/ufo/pull/87) resulting in the leading slash being removed.
> fix(parseURL): only normalize windows drive letters with `file://` protocol

- src/utils.ts
- test/utilities.test.ts
Resolve: #241 
Add protocol relative behaviour
Reference links on relative protocol
- <https://stackoverflow.com/a/9646435>
- <https://stackoverflow.com/questions/550038/is-it-valid-to-replace-http-with-in-a-script-src-http>
- <https://stackoverflow.com/a/960111>
> fix(withProtocol): consider relative protocol

- README.md
- src/encoding.ts
- src/parse.ts
- src/query.ts
- src/utils.ts
Fixes some very minor spelling mistakes and ensures `URL` is always written uppercase.
This is mainly for the JSDoc comment reader/enthusiasts, like me. 😄 
This PR also fixes the `automd` syntax in the README, which was broken and failed to generate the latest docs from the JSDocs.
> chore: consistent spelling in JSDoc comments & update automd syntax

- src/utils.ts
- The docs for `withBase` incorrectly referred to a trailing slash instead of the `base` string
- Minor typos and grammar fixes
> docs: clarify `withBase` jsdocs

- src/query.ts
- test/query.test.ts
> fix(parseQuery): use object with null prototype

- README.md
- src/parse.ts
- test/parse.test.ts
Resolves #283 
This PR, for `parseFilename`
- Fixes incorrect access of options 
- Exposes a `ParseFilenameOptions` interface
- Refactors tests for readability improvements and adding cases without options
> fix(parseFilename): use optional chaining to access `opts.strict`

- src/query.ts
resolve an ecosystem regrerssion introduced from #286 
Using a custom class with null prototype adds [performance benefits](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJQdEZfRWZzQzFVWjRaTXBTU1BWTG4iLCJjb2RlIjoiQXJyYXkuZnJvbSh7bGVuZ3RoOiAxMDAwMH0sICgpID0-IG5ldyBEQVRBLkVtcHR5T2JqZWN0KCkpIiwibmFtZSI6IkVtcHR5T2JqZWN0IiwiZGVwZW5kZW5jaWVzIjpbXX0seyJpZCI6Ink4ZHkxeS1ENV8xV3lDeUFRaEJZNyIsImNvZGUiOiJBcnJheS5mcm9tKHtsZW5ndGg6IDEwMDAwfSwgKCkgPT4gREFUQS5PYmplY3RDcmVhdGUoKSkiLCJuYW1lIjoiT2JqZWN0Q3JlYXRlIiwiZGVwZW5kZW5jaWVzIjpbXX1dLCJjb25maWciOnsibmFtZSI6IkJhc2ljIGV4YW1wbGUiLCJwYXJhbGxlbCI6dHJ1ZSwiZ2xvYmFsVGVzdENvbmZpZyI6eyJkZXBlbmRlbmNpZXMiOltdfSwiZGF0YUNvZGUiOiJjb25zdCBFbXB0eU9iamVjdCA9IC8qIEBfX1BVUkVfXyAqLyAoKCkgPT4ge1xuICBjb25zdCBDID0gZnVuY3Rpb24gKCkge307XG4gIEMucHJvdG90eXBlID0gT2JqZWN0LmNyZWF0ZSh …
> fix(query): use `Object.create(null)`

- README.md
- src/parse.ts
- src/query.ts
- src/utils.ts
In this PR, I’ve added JSDoc comments to most of the utility functions, in the hope that these examples can help users better understand the purpose and usage of each function.
Perhaps we could also consider including some of them in the README?
> docs: add more examples in jsdoc
